spring :
  datasource:
    url: jdbc:postgresql://localhost:5430/exam
    username: postgres
    password: Vu123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
server:
  port: 1997
appConfig:
  default-page-size: 10
  default-page-number: 0